server:
  port: 8086
  #servlet:
    #context-path: /api

spring:
  application:
    name: sbms_sample_api
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbms_sample_api?createDatabaseIfNotExist=true&autoReconnect=true
    username: root
    password: root
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect          
      
  #profiles:
    #active: local

app:
  task:
    executor:
      corePoolSize: 4
      maxPoolSize: 8
      threadNamePrefix: SBMS_SAMPLE_API
  language:
    supported:
      - in
      - en
    primary: in
  cache:
    configuration:
      host: 
    groups:
      - name: ACCESS
        limit: 100
        age: 3600000
        nullable: true
        collector: accessCollector
      - name: test
        limit: 100
        age: 30000
        nullable: true
        collector: 
      - name: coba
        limit: 100
        age: 30000
        nullable: false
        collector: 
  remote-method-services:
    - com.ideahut.sbms.sample.client.service.TestService
  ignored-handler-classes:
    - springfox.documentation.swagger.web.ApiResourceController
    
    
        
swagger:
  package: com.idh.ms.core.controller
  info:
    title: Microservice Sample
    license: IDEAHUT
    licenseUrl: https://github.com/ideahut
    termsOfServiceUrl: https://github.com/ideahut
    description: Microservice Sample
    version: 1.0.0    
    
      
logging:
  file: /var/log/sbms_sample_api.log
  pattern:
    console: '%d %p [%X{traceId}] %F\(%M:%L\) : %msg%n'
    file: '%d %p [%X{traceId}] %F\(%M:%L\) : %msg%n'
  level:
    org:
      hibernate: INFO
      springframework: INFO
    com:
      ideahut:
        sbms:
          sample:
            api: DEBUG
  
cors:
  origin: "*"
  headers: X-Requested-With, Content-Type, Accept, Origin, Authorization
  methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
  credentials: true
  maxage: 3600



