server:
  port: 8088
  #servlet:
    #context-path: /view

spring:
  application:
    name: sbms_sample_view
  main:
    banner-mode: "off"  
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    view: 
      prefix: /WEB-INF/pages/
      suffix: .jsp
  #datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/microservice_template?createDatabaseIfNotExist=true&autoReconnect=true
    #username: root
    #password: root
  #jpa:
    #database: MYSQL
    #show-sql: false
    #hibernate:
      #ddl-auto: update
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQL5InnoDBDialect          
  #jackson:
    #default-property-inclusion: non_null
  #profiles:
    #active: local

app:
  task:
    executor:
      corePoolSize: 4
      maxPoolSize: 8
      threadNamePrefix: SBMS_SAMPLE_VIEW
  language:
    supported:
      - in
      - en
    primary: in
  initial:
    page: /home
    theme: theme-red
      


logging:
  file: /var/log/sbms_sample_view.log
  pattern:
    console: '%d %p [%X{traceId}] %F\(%M:%L\) : %msg%n'
    file: '%d %p [%X{traceId}] %F\(%M:%L\) : %msg%n'
  level:
    org:
      hibernate: INFO
      springframework: INFO
    com:
      ideahut:
        sbms:
          sample:
            api: DEBUG